version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - petrol_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  petrol_data:
